import yaml
import os
import re
from pathlib import Path

def extract_civitai_version(urn: str) -> str:
    """Extracts the model version ID from a URN."""
    if '@' in urn:
        return urn.split('@')[-1]
    match = re.search(r'(\d+)$', urn)
    if match:
        return match.group(1)
    return ""

def generate_enums():
    registry_dir = Path(__file__).parent
    yaml_path = registry_dir / "models.yml"
    output_path = registry_dir / "generated_enums.py"
    
    if not yaml_path.exists():
        print(f"Error: {yaml_path} not found.")
        return

    with open(yaml_path, "r", encoding="utf-8") as f:
        data = yaml.safe_load(f)
        
    lines = [
        "# Autogenerated file (DO NOT EDIT MANUALLY)",
        "from enum import Enum",
        ""
    ]
    
    if data:
        for enum_name, enum_values in data.items():
            lines.append(f"class {enum_name}(Enum):")
            if not enum_values:
                lines.append("    pass")
            else:
                for key, val in enum_values.items():
                    safe_key = str(key).upper().replace("-", "_").replace(".", "_")
                    
                    if isinstance(val, dict):
                        if val.get("provider") == "civitai" and "urn" in val:
                            val["model_version_id"] = extract_civitai_version(val["urn"])
                    
                    val_str = repr(val)
                    lines.append(f'    {safe_key} = {val_str}')
            lines.append("")
            
    with open(output_path, "w", encoding="utf-8") as f:
        f.write("\n".join(lines))
        
    print(f"Successfully generated {output_path}")

if __name__ == "__main__":
    generate_enums()
