# Autogenerated file (DO NOT EDIT MANUALLY)
from enum import Enum

class Checkpoints(Enum):
    FLUX_DEV = {'provider': 'huggingface', 'repo_id': 'black-forest-labs/FLUX.1-dev'}
    FLUX_SCHNELL = {'provider': 'huggingface', 'repo_id': 'black-forest-labs/FLUX.1-schnell'}
    DREAMSHAPER = {'provider': 'civitai', 'url': 'https://civitai.com/models/4384/dreamshaper', 'urn': 'urn:air:sd1:checkpoint:civitai:4384@128713', 'model_version_id': '128713'}

class Vae(Enum):
    AE = {'provider': 'huggingface', 'repo_id': 'black-forest-labs/FLUX.1-dev-ae'}

class Clip(Enum):
    CLIP_L = {'provider': 'huggingface', 'repo_id': 'openai/clip-vit-large-patch14'}
    T5XXL = {'provider': 'huggingface', 'repo_id': 'google/t5-v1_1-xxl'}

class Upscalers(Enum):
    ESRGAN_4X = {'provider': 'openmodeldb', 'url': 'https://huggingface.co/tsunemori/esrgan/resolve/main/4x_ESRGAN.pth', 'filename': '4x_ESRGAN.pth'}
