import yaml
import os
import re
import argparse
from pathlib import Path

def generate_enums(yaml_path: Path, output_path: Path):
    if not yaml_path.exists():
        print(f"Error: {yaml_path} not found.")
        return

    with open(yaml_path, "r", encoding="utf-8") as f:
        data = yaml.safe_load(f)
        
    lines = [
        "# Autogenerated file (DO NOT EDIT MANUALLY)",
        "from enum import Enum",
        ""
    ]
    
    if data:
        for enum_name, enum_values in data.items():
            lines.append(f"class {enum_name}(Enum):")
            if not enum_values:
                lines.append("    pass")
            else:
                for key, val in enum_values.items():
                    safe_key = str(key).upper().replace("-", "_").replace(".", "_")
                    
                    val_str = repr(val)
                    lines.append(f'    {safe_key} = {val_str}')
            lines.append("")
            
    with open(output_path, "w", encoding="utf-8") as f:
        f.write("\n".join(lines))
        
    print(f"Successfully generated {output_path}")

def main():
    parser = argparse.ArgumentParser(description="Generate Enums from models.yml")
    parser.add_argument("--input", type=str, default="models.yml", help="Path to models.yml")
    parser.add_argument("--output", type=str, default="generated_enums.py", help="Output python file path")
    
    args = parser.parse_args()
    
    input_path = Path(args.input)
    output_path = Path(args.output)
    
    generate_enums(input_path, output_path)

if __name__ == "__main__":
    main()
